---
# Simple connectivity test playbook
- name: Test connectivity to all nodes
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping test
      ping:
      
    - name: Gather basic facts
      setup:
        gather_subset:
          - min
          - network
      
    - name: Display node info
      debug:
        msg: |
          Hostname: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          IP: {{ ansible_default_ipv4.address | default('No IP') }}
          Tailscale: {{ ansible_facts['ansible_tailscale0'] is defined | ternary('Connected', 'Not found') }}